### ISSUE TITLE
[Media] Can't upload an image on Qarnot (QuotaExceeded)

### ISSUE THREAD

**Issue by florianriche** [pyronear/pyro-api#158]
Trying to upload a media using the following snippet:

```python
import requests
from pyroclient import client
API_URL = "http://pyronear-api.herokuapp.com"
CREDENTIALS_LOGIN = <deviceLogin>
CREDENTIALS_PASSWORD = <devicePassword>
api_client = client.Client(API_URL, CREDENTIALS_LOGIN, CREDENTIALS_PASSWORD)
#AS A DEVICE:
## Create a device
event_id = api_client.create_event(lat=12, lon=10).json()["id"]
## Create a media
media_id = api_client.create_media_from_device().json()["id"]
## Create an alert linked to the media and the event
api_client.send_alert_from_device(lat=13, lon=10, event_id=event_id, media_id=media_id)
# Upload an image on the media
dummy_image = "https://ec.europa.eu/jrc/sites/jrcsh/files/styles/normal-responsive/" \
                    + "public/growing-risk-future-wildfires_adobestock_199370851.jpeg"
image_data = requests.get(dummy_image)
api_client.upload_media(media_id=media_id, media_data=image_data.content)
```

yields a 500 Exception with the following message: `{'detail': 'Failed upload'}`

If we look at the logs from the API and we add a stacktrace, we get the following:

```
Exception: An error occurred (QuotaExceeded) when calling the PutObject operation: Unknown
Traceback (most recent call last):
  File "./app/services/bucket/qarnot.py", line 81, in upload_file
    self.bucket.add_file(file_binary, bucket_key)
  File "/usr/local/lib/python3.8/site-packages/qarnot/bucket.py", line 302, in add_file
    self._connection.s3client.upload_fileobj(file_, self._uuid, dest, Config=s3_multipart_config)
  File "/usr/local/lib/python3.8/site-packages/boto3/s3/inject.py", line 539, in upload_fileobj
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/usr/local/lib/python3.8/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/usr/local/lib/python3.8/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/usr/local/lib/python3.8/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/s3transfer/upload.py", line 692, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 676, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (QuotaExceeded) when calling the PutObject operation: Unknown
WARNING:  An error occurred (QuotaExceeded) when calling the PutObject operation: Unknown
INFO:     172.30.0.1:57072 - "POST /media/3/upload HTTP/1.1" 500 Internal Server Error
```

I didn't find many references to that Exception (QuotaExceeded) on Google and looking at the Qarnot Console, I don't think we are out of Quota (to double check as it has been months since the last time I went to see the console).

Could it be that there is an issue on S3 usage by Qarnot? It has been months since the last time we uploaded a media soo it is hard to know when the issue arose.
Any thought @pyronear/back-end  ?

**Comment by frgfm** [comment]
I think I know the origin of the problem: we used all our storage on Qarnot due to a dataset upload attempt.
I just fixed that, could you check if this solved the problem?

**Comment by florianriche** [comment]
Ok good then. 
I tried to delete a few media but it didn't solve the problem. Apparently deleting on the dataset side is working though. Fair enough. Good that it is solved.

**Comment by frgfm** [comment]
All good
